# Generated by Django 2.0.5 on 2018-11-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='rotation',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('not_allowed', 'Not Allowed')], default='allowed', max_length=20),
        ),
    ]
